### ISSUE TITLE
WinRT event handler / GenericTypeModifier

### ISSUE THREAD

**Issue by srtonz** [timsneath/win32#389]
Not that #370 has been closed I was hoping to get BLE device discovery and communication going.

Unfortunately the `BluetoothFindFirstDevice` function [does not work for BLE devices](https://docs.microsoft.com/en-us/windows/win32/api/bluetoothapis/nf-bluetoothapis-bluetoothfindfirstdevice#remarks), and instead it's recommended to use the [`BluetoothLEAdvertisementWatcher`](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementwatcher?view=winrt-22000) class for finding nearby BLE devices.

I've been able to make some progress toward this (thanks to the Calendar example), but I'm struggling to understand how to add event handlers for `Received`and `Stopped` events. Running the `generate.cmd` script with some debug modifications this is the error it's generating:

```dart
Projecting method: add_Received
Unable to project method: add_Received
Exception: Type information missing for GenericTypeModifier, TYPE: Windows.Foundation.TypedEventHandler`2.
#0      TypeProjection.projectType (file:///C:/Projects/win32/tool/projection/type.dart:246:5)
#1      TypeProjection.projection (file:///C:/Projects/win32/tool/projection/type.dart:54:21)
#2      TypeProjection.dartType (file:///C:/Projects/win32/tool/projection/type.dart:63:26)
#3      ParameterProjection.dartProjection (file:///C:/Projects/win32/tool/projection/parameter.dart:20:37)
#4      MethodProjection.methodParams.<anonymous closure> (file:///C:/Projects/win32/tool/projection/method.dart:76:42)
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#6      ListIterable.join (dart:_internal/iterable.dart:165:22)
#7      MethodProjection.methodParams (file:///C:/Projects/win32/tool/projection/method.dart:76:62)
#8      WinRTMethodProjection.toString (file:///C:/Projects/win32/tool/projection/winrt_method.dart:86:37)
#9      InterfaceProjection.toString.<anonymous closure> (file:///C:/Projects/win32/tool/projection/interface.dart:201:42)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#11     ListIterable.join (dart:_internal/iterable.dart:156:22)
#12     InterfaceProjection.toString (file:///C:/Projects/win32/tool/projection/interface.dart:201:54)
#13     generateWinRTApis (file:///C:/Projects/win32/tool/generation/generate_winrt_apis.dart:27:43)
#14     main (file:///C:/Projects/win32/tool/generation/generate.dart:36:3)
#15     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
``` 

I'd be happy to give this a go, but unsure where to start and whether this is currently possible at all?

**Comment by timsneath** [comment]
Grr... That's really infuriating that the Win32 APIs are half-implemented. Why do they have the other `BluetoothGatt` functions if you can't find devices? :( The endless Microsoft back-and-forth on preferred APIs keeps bringing the pain.

Unfortunately, the WinRT projection classes are in a very preliminary state. I've been making some progress this weekend, ironically, but I don't yet have event handlers or WinRT generics supported. So yeah, this is not possible without significant future iteration on the projection work.

**Comment by Sunbreak** [comment]
I would `NOT` recommand `Dart projection on WinRT` for BluetoothLE for now

Actually you have two options

1. Call `C++/WinRT` APIs via MethodChannel or `dart:ffi`

- MethodChannel example on BLE: https://github.com/woodemi/quick_blue
- `dart:ffi` example on USB: https://github.com/woodemi/quick_usb
- `dart:ffi` example on `cronet`: https://github.com/Sunbreak/cronet_flutter

2. Call `SetupAPI` and APIs inside [`bthledef.h`](https://docs.microsoft.com/en-us/windows/win32/api/bthledef/)

- Search blutoothLE service: https://gist.github.com/programmarchy/c9d02e22d58bfab3f8bb
- List bluetoothLE device: https://gist.github.com/neolit123/e44feaf4babc7c4997f54af014a026e9
- List bluetoothLE device: https://www.silabs.com/content/usergenerated/asi/cloud/attachments/siliconlabs/en/community/wireless/bluetooth/forum/jcr:content/content/primary/qna/i_cant_receive_data-Z8QJ/thank_you_very_much-wmty/TestBLE.c

**Comment by Sunbreak** [comment]
Related PR: https://github.com/timsneath/win32/pull/392

- Chrome source code on BLE: https://chromium.googlesource.com/chromium/src/+/32352ad08ee673a4d43e8593ce988b224f6482d3/device/bluetooth/bluetooth_low_energy_defs_win.h
- Chrome source code on HID: https://chromium.googlesource.com/chromium/src/+/80a586198d12e1a6d02cac715e2ac88bf5d0e565/device/hid/hid_service_win.cc

**Comment by srtonz** [comment]
Thanks both. We already have a working C++/WinRT implementation to use for now, this was really just trying to see how far we can push things into Dart "only". Feel free to ping me here if you need contributions in the future.

**Comment by azimuthdeveloper** [comment]
@srtonz it's a long shot, but is your implementation open source by any chance? Just getting into the BLE space quite a bit and am having simiilar issues getting BLE to work with Flutter.

**Comment by srtonz** [comment]
@azimuthdeveloper that was the intention originally, but work didn't progress beyond prototyping. At the moment a combination of `flutter_reactive_ble` and `quick_blue` (for Desktop) is working for us.
